source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SimplePDF_Example' do
  pod 'SimplePDFSwift', :path => '../'
end

target 'SimplePDF_Tests' do
  pod 'SimplePDFSwift', :path => '../'

  pod 'Quick', git: 'https://github.com/Quick/Quick.git', branch: 'swift-3.0'
  pod 'Nimble', git: 'https://github.com/martnst/Nimble.git', branch: 'swift3'
end
